#!/usr/bin/env python3
import json
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT / "openapi" / "public.json"
SPEC_PATH = Path(os.environ.get("CRAWLORA_OPENAPI_SPEC", DEFAULT_SPEC))
TAG_GROUP_OVERRIDES = {
    "AppStore": "appStore",
    "CoinGecko": "coinGecko",
    "GooglePlay": "googlePlay",
    "ProductHunt": "productHunt",
    "SimilarWeb": "similarWeb",
    "SpotifyPodcasts": "spotifyPodcasts",
    "TikTok": "tiktok",
    "YouTube": "youtube",
}
TAG_PREFIX_OVERRIDES = {
    "AppStore": "appstore",
    "CoinGecko": "coingecko",
    "GooglePlay": "googleplay",
    "ProductHunt": "producthunt",
    "SimilarWeb": "similarweb",
    "SpotifyPodcasts": "spotify-podcasts",
    "TikTok": "tiktok",
    "YouTube": "youtube",
}


def words(value):
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return [part for part in re.split(r"[^A-Za-z0-9]+", value.lower()) if part]


def camel(parts):
    if not parts:
        return "call"
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def alias(operation_id, tag, used):
    op_words = words(operation_id)
    tag_words = words(TAG_PREFIX_OVERRIDES.get(tag, tag))
    if op_words[: len(tag_words)] == tag_words:
        op_words = op_words[len(tag_words) :]
    name = camel(op_words)
    if not name or name in used:
        name = camel(words(operation_id))
    base = name
    i = 2
    while name in used:
        name = f"{base}{i}"
        i += 1
    used.add(name)
    return name


def operation_definition(operation_id, method, path, operation):
    params = operation.get("parameters", [])
    security = []
    for requirement in operation.get("security", []):
        security.extend(requirement.keys())
    return {
        "id": operation_id,
        "method": method.upper(),
        "path": path,
        "pathParams": [p["name"] for p in params if p.get("in") == "path"],
        "queryParams": [
            {
                "name": p["name"],
                **({"collectionFormat": p["collectionFormat"]} if "collectionFormat" in p else {}),
                **({"type": p["type"]} if "type" in p else {}),
                **({"required": True} if p.get("required") else {}),
                **({"enum": [str(v) for v in p["enum"]]} if p.get("enum") else {}),
            }
            for p in params
            if p.get("in") == "query"
        ],
        "formParams": [
            {
                "name": p["name"],
                **({"type": p["type"]} if "type" in p else {}),
                **({"required": True} if p.get("required") else {}),
                **({"enum": [str(v) for v in p["enum"]]} if p.get("enum") else {}),
            }
            for p in params
            if p.get("in") == "formData"
        ],
        "bodyParam": next((p["name"] for p in params if p.get("in") == "body"), None),
        "consumes": operation.get("consumes", []),
        "produces": operation.get("produces", []),
        "security": security,
    }


def main():
    if not SPEC_PATH.exists():
        raise SystemExit(f"public OpenAPI spec not found: {SPEC_PATH}")
    spec = json.loads(SPEC_PATH.read_text())
    (ROOT / "openapi").mkdir(exist_ok=True)
    target_spec = ROOT / "openapi" / "public.json"
    if SPEC_PATH.resolve() != target_spec.resolve():
        shutil.copyfile(SPEC_PATH, target_spec)

    operations = {}
    grouped = {}
    used_by_group = {}
    for path, methods in sorted(spec["paths"].items()):
        for method, operation in sorted(methods.items()):
            operation_id = operation["operationId"]
            tag = (operation.get("tags") or ["default"])[0]
            group_name = TAG_GROUP_OVERRIDES.get(tag, camel(words(tag)))
            grouped.setdefault(group_name, {})
            used_by_group.setdefault(group_name, set())
            method_name = alias(operation_id, tag, used_by_group[group_name])
            operations[operation_id] = operation_definition(operation_id, method, path, operation)
            grouped[group_name][method_name] = operation_id

    content = (
        "// Generated by scripts/generate.py. Do not edit manually.\n"
        f"export const operations = {json.dumps(operations, indent=2, sort_keys=True)};\n\n"
        f"export const groups = {json.dumps(grouped, indent=2, sort_keys=True)};\n\n"
        f"export const operationCount = {sum(len(methods) for methods in spec['paths'].values())};\n"
    )
    (ROOT / "src" / "operations.js").write_text(content)


if __name__ == "__main__":
    main()
